/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test public void rollTest(){
        Library rolltses=new Library();
        int [] arrofint=rolltses.roll(2);
        assertEquals(arrofint.length,2);
    }

    @Test public void DuplicatesTest(){
        Library rolltses=new Library();
        int [] arr={1,1,3};
        boolean test  =rolltses.containsDuplicates(arr);
        assertEquals(test,true);
    }

    @Test public void avgTest(){
        Library rolltses=new Library();
        int [] arr={1,2,3};
        float test  =rolltses.avg(arr);
        assertEquals(test,2);
    }

    @Test public void avg2dimensionTest(){
        Library rolltses=new Library();
        int [][] arr={{1,2,3},{1,2,3}};
        float test  =rolltses.avg2dimension(arr);
        assertEquals(test,2);
    }





}
