/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.Random;
import java.util.Arrays;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        System.out.println("hello world");
        int [] aay=roll(5);
        System.out.println(Arrays.toString(aay));
        int [] aray1={1,1,2,3};
        boolean doublicate=containsDuplicates(aray1);
        System.out.println(doublicate);
        float average=avg(aray1);
        System.out.println(average);
        int [][] arr3={{1,2,3},{1,2,3}};
        float avgtwo=avg2dimension(arr3);
        System.out.println(avgtwo);

    }


   public static int[] roll(int num) {
        System.out.println("hello world");
        int [] arr=new int[num];
        Random rand=new Random();
        for(int i=0;i<num;i++){
            int x = rand.nextInt(5);
            x++;
            arr[i]=x;
        }
        return arr;
    }

    public static boolean containsDuplicates  (int[] arr) {
        boolean  containsDuplication=false;
for(int i=0;i<arr.length;i++){
    for(int j=0;j< arr.length;j++){
        if(i ==j){
            continue;
        }else {
            if(arr[i] == arr[j]){
                containsDuplication=true;
                break;
            }
        }


    }

    if(containsDuplication ==true){
        break;
    }
}
return containsDuplication;

    }


    public static float avg(int [] num){
        float sum=0;
        for(int i=0;i< num.length;i++){
            sum+=num[i];
        }

      return sum/ num.length;
    }
    public static float avg2dimension(int [][] arr){
        float sum=0;
        int size=0;
        for(int i=0;i< arr.length;i++){
            for (int k=0;k<arr[i].length;k++){
                sum+=arr[i][k];
                size++;
            }

        }
        return sum/size;

    }


}

