/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        System.out.println("Hello");
        Restaurant falafel=new Restaurant("falafel",4,1);
        Restaurant shaWarma=new Restaurant("shaWarma",3,2);
        Restaurant manSaf=new Restaurant("manSaf",4,5);

        System.out.println( falafel.toString());
        System.out.println( shaWarma.toString());
        System.out.println( manSaf.toString());

        Review newReview=new Review("mohammed","its good resturent",5);
        System.out.println(newReview.toString());

    }
}
