/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        Restaurant testResturantt=new Restaurant("kabab",5,10);
        System.out.println(testResturantt.toString());

        System.out.println("Hello");
        Restaurant falafel=new Restaurant("falafel",6,1);
        Restaurant shaWarma=new Restaurant("shaWarma",3,2);
        Restaurant manSaf=new Restaurant("manSaf",4,5);
        falafel.addReview("mohammed","its good resturent",4);
       Shop bookShoop=new Shop("book",4,5);
        System.out.println(bookShoop.toString());

        Theater cienema=new Theater("cienema");
        cienema.addMovie("shawshank redumption");
        cienema.addMovie("The god father");
        cienema.removeMovie("shawshank redumption");
        cienema.displayMovies();
        cienema.addReview("mohammed mosleh","its good cienema",4,"shawshankredumption");
        System.out.println(cienema.toString());
        System.out.println(falafel.toString());
        cienema.addReview("khader","bad cienema",4);
        System.out.println(cienema.toString());

        Shop macdonalds=new Shop("macdonalds",2,5);
        macdonalds.addReview("Mohammed","good",5);
        System.out.println(macdonalds.toString());


    }
}
