/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linterlinter;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        int errors= check("gates.txt");
        System.out.println(errors);

    }

    public static int  check(String path1){
        Path path = Paths.get(path1);
        int numOferror=-1;

        try {
            ArrayList <String> arrOferrors=new ArrayList <> ();
            int numOfline=0;
            List<String> fileLines = Files.readAllLines(path);
            for(String line : fileLines){
                numOfline++;
                //  System.out.println(line.length());
           if(! line.isEmpty()){
               char charr=  line.charAt(line.length() - 1);
            System.out.println(charr);
               boolean containIforelse= line.contains("if");
               if(! (charr ==';' ||charr == '{' ||charr =='}' || containIforelse) ){
                   System.out.println("Line "+numOfline+" : Missing semicolon.");
                   numOferror++;

               }
           }


            }
        } catch (IOException exception){
            System.out.println("An error occurred while reading from file");
        }


        return numOferror;
    }
}
