/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test
    public void resturantTest() {
        Restaurant testResturantt=new Restaurant("kabab",5,10);


        assertEquals("Restaurant{name='kabab', stars=5, price=10}",testResturantt.toString());
    }

    @Test
    public void reviewTest() {
        Review testReviw=new Review("Mohammed","good",5);
        assertEquals("Review{author='Mohammed', body='good', numOfstars=5}",testReviw.toString());
    }

    @Test
    public void addReviewTest() {
        Restaurant ward=new Restaurant("ward",5,20);
        ward.addReview("Mohammed","good",5);
        assertEquals(1,ward.listreview.size());
    }

    @Test
    public void starratingTest() {
        Restaurant macdonalds=new Restaurant("macdonalds",2,5);
        macdonalds.addReview("Mohammed","good",5);
        macdonalds.addReview("Ahmed","good",0);
        macdonalds.addReview("Yousef","bad",4);
        assertEquals(3,macdonalds.stars);
    }



}
